spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:50000}/${POSTGRES_DB:admin_bd}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.access.secret=7Yp2QZJkN6xM9H8Wc4FvR0L1uA+EwX3Tq5S/9mDObaJrKZVtCsiUeYlPhg==
jwt.refresh.secret=Qw9fK3M1rT8bS+E4V6yA0D2LJXxZpHcN5UFeo7WgYI/kBmaRsdnCOT==
jwt.access.ttl-minutes=${JWT_ACCESS_TTL_MINUTES:15}
jwt.refresh.ttl-hours=${JWT_REFRESH_TTL_HOURS:168}